version: "3.9"
services:
  relay:
    build: ./relay
    image: void/relay:latest
    restart: unless-stopped
    environment:
      - PORT=${PORT:-8787}
      - RELAY_API_KEY=${RELAY_API_KEY}
    ports:
      - "${PORT:-8787}:8787"
    networks: [voidnet]

  ipfs-poller:
    build: ./ipfs-poller
    image: void/ipfs-poller:latest
    restart: unless-stopped
    environment:
      - IPFS_GW=${IPFS_GW:-https://cloudflare-ipfs.com/ipfs/}
      - CIDS=${CIDS}
      - INTERVAL_SEC=${INTERVAL_SEC:-30}
      - DEGRADED_MS=${DEGRADED_MS:-1500}
      - RELAY_URL=${RELAY_URL:-http://relay:8787/event}
      - RELAY_API_KEY=${RELAY_API_KEY_POLL:-${RELAY_API_KEY}}
    depends_on: [relay]
    networks: [voidnet]

networks:
  voidnet: {}
