name: k6-gate
on: [push, pull_request]
jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install & build server
        working-directory: server
        run: npm ci && npm run build && node dist/index.js &
      - name: Wait
        run: sleep 2
      - name: Run k6
        uses: grafana/k6-action@v0.3.1
        with:
          filename: k6/codex-load.js
          flags: --vus 10 --duration 30s -e BASE=http://localhost:8788
