services:
  opa-pdp:
    image: openpolicyagent/opa:latest
    command: ["run", "--server", "--addr=0.0.0.0:8181", "/policies"]
    volumes:
      - ../opa/policies:/policies:ro
    ports:
      - "8181:8181"
    networks: [ voidnet ]
networks:
  voidnet: { external: true }
