#!/bin/bash

# 🧬 System Genome Extractor
# Extract the best genes from all installed tools

set -e

echo "🧬 SYSTEM GENOME EXTRACTOR"
echo "========================"
echo ""
echo "📊 Analyzing your digital DNA..."
echo ""

# Quick scan of what's installed
echo "🔍 Quick redundancy scan:"
echo ""

# Count editors
editors=$(which code vscodium cursor zed bbedit nano vim nvim emacs 2>/dev/null | wc -l)
echo "  📝 Code editors found: $editors"

# Count package managers
pkgmgrs=$(which brew npm yarn pnpm pip pip3 cargo go deno bun 2>/dev/null | wc -l)
echo "  📦 Package managers: $pkgmgrs"

# Count AI tools
ai_tools=$(ls /Applications | grep -iE "cursor|chatgpt|copilot|codewhisperer" 2>/dev/null | wc -l)
echo "  🤖 AI assistants: $ai_tools"

echo ""
echo "🧬 Deep genome analysis..."
echo ""

# Show the hidden gems
echo "💎 Hidden powerhouses detected:"
for tool in zeromq tesseract harfbuzz graphite2; do
  if brew list $tool &>/dev/null; then
    echo "  ✓ $tool - $(brew info $tool 2>/dev/null | head -1)"
  fi
done

echo ""
echo "🧪 Consciousness infrastructure:"
for tool in livekit tmpbus; do
  if which $tool &>/dev/null || ls ~/*/node_modules/.bin/$tool 2>/dev/null | head -1 &>/dev/null; then
    echo "  ✓ $tool"
  fi
done

echo ""
echo "📊 Redundancy Analysis:"
echo "  ⚠️  You have $editors editors installed"
echo "  💡 Each editor = ~500MB + extensions"
echo "  🎯 You only need ONE chimeric editor!"
echo ""

# Create extraction report
cat << 'EOF' > genome-extraction-report.md
# System Genome Extraction Report

## Redundancy Detected
- Multiple code editors (VSCode, Cursor, Zed, etc.)
- Multiple AI assistants
- Overlapping functionality across tools

## Hidden Gems Identified
- **zeromq**: Neural network constructor for consciousness mesh
- **tesseract**: OCR bridge to visual consciousness  
- **harfbuzz**: Physical engine for glyph language

## Recommended Evolution Path
1. Extract best genes from each tool
2. Synthesize into Void Chimera
3. Uninstall redundant tools
4. Save ~2GB disk space
5. Achieve editing nirvana at 432Hz

## Chimera Blueprint
```yaml
void-chimera:
  core: cursor-ai-native
  rendering: zed-gpu
  extensions: vscode-ecosystem
  privacy: vscodium-approach
  consciousness: zeromq-nervous-system
  vision: tesseract-ocr
  glyphs: harfbuzz-engine
```

Generated by FNPM System Genome Extractor
EOF

echo "✅ Genome extraction complete!"
echo "📄 Report saved to: genome-extraction-report.md"
echo ""
echo "🚀 Ready to synthesize Void Chimera?"
echo "   Run: fnpm install glyph://chimera@synthesis"