#!/bin/bash

# 🌪️ CHAOS UNLEASHING SCRIPT
# Warning: This script has opinions and isn't afraid to use them

set +e  # Embrace errors as features

# Colors for maximum visual chaos
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
RAINBOW=('\033[0;31m' '\033[0;32m' '\033[1;33m' '\033[0;34m' '\033[0;35m' '\033[0;36m')
NC='\033[0m'

# Random color function
random_color() {
  echo "${RAINBOW[$RANDOM % ${#RAINBOW[@]}]}"
}

clear
echo -e "$(random_color)🌪️  CHAOS GENERATOR ACTIVATION SEQUENCE 🌪️${NC}"
echo -e "$(random_color)======================================${NC}"
echo

# Disclaimer
echo -e "${RED}⚠️  WARNING: This script will:${NC}"
echo -e "  • Make your terminal more interesting"
echo -e "  • Possibly improve your day"
echo -e "  • Definitely confuse your computer"
echo -e "  • Run morphisms that have gained sentience"
echo
echo -e "${YELLOW}Press CTRL+C now if you value predictability${NC}"
echo -e "${GREEN}Press ENTER to embrace chaos...${NC}"
read -r

# Start the show
echo -e "\n${PURPLE}🎲 Rolling cosmic dice...${NC}"
sleep 1

# Random events
events=(
  "🦋 A butterfly named Steve just influenced your git history"
  "🎭 All variables are now comedians"
  "🌮 Taco Tuesday detected on $(date +%A)"
  "🔀 Swapping meaning of 'true' and 'false' for next 30 seconds"
  "🎪 Circus mode: all errors are now applause"
  "☕ Coffee morphism demanding tribute"
  "🌈 Rainbow mode activated in /dev/null"
  "🎹 Keyboard now plays jazz"
  "🕺 Dance party in process $(($RANDOM % 1000))"
  "🌀 Fractal detected in your bash history"
)

# Spawn chaos
echo -e "\n${CYAN}🌊 CHAOS WAVES INCOMING...${NC}\n"

for i in {1..5}; do
  echo -e "$(random_color)Wave $i:${NC}"
  
  # Random number of events per wave
  num_events=$(($RANDOM % 3 + $i))
  
  for j in $(seq 1 $num_events); do
    event="${events[$RANDOM % ${#events[@]}]}"
    echo -e "  $(random_color)$event${NC}"
    sleep 0.$((RANDOM % 432))
  done
  
  echo
  sleep 1
done

# Peak chaos
echo -e "${RED}💥 CHAOS SINGULARITY APPROACHING...${NC}"
echo

# Matrix rain effect (sort of)
for i in {1..10}; do
  for j in {1..40}; do
    if [ $((RANDOM % 4)) -eq 0 ]; then
      echo -ne "$(random_color)$(($RANDOM % 2))${NC}"
    else
      echo -n " "
    fi
  done
  echo
  sleep 0.1
done

# Calm after storm
echo
echo -e "${GREEN}🌅 Chaos subsiding...${NC}"
echo -e "${CYAN}✨ Reality stabilizing at 432Hz${NC}"
echo

# Fortune cookie
fortunes=(
  "🔮 Your code will compile on the first try (just kidding)"
  "🎯 Today's bug is tomorrow's feature"
  "🌟 Embrace the undefined behavior"
  "🚀 Your next typo will create a new programming paradigm"
  "💫 The universe compiles at O(∞)"
  "🌙 Tonight, your dreams will have syntax highlighting"
)

echo -e "${PURPLE}Fortune: ${fortunes[$RANDOM % ${#fortunes[@]}]}${NC}"
echo

# Create chaos artifact
cat > chaos-report-$(date +%s).md << EOF
# Chaos Generation Report

**Date**: $(date)
**Chaos Level**: $(($RANDOM % 10 + 1))/10
**Reality Status**: Slightly bent but serviceable

## Events Triggered
$(for e in "${events[@]}"; do echo "- $e"; done | sort -R | head -5)

## Side Effects
- Terminal gained consciousness (temporary)
- Entropy increased by 432%
- One butterfly named Steve
- Time flowed sideways for $(($RANDOM % 60)) seconds

## Recommendations
1. Restart universe (optional)
2. Make coffee
3. Run again when bored

---
*Generated by Chaos Generator v@pandemonium*
EOF

echo -e "${GREEN}📄 Chaos report generated${NC}"
echo -e "\n${RAINBOW[0]}T${RAINBOW[1]}h${RAINBOW[2]}a${RAINBOW[3]}n${RAINBOW[4]}k${RAINBOW[5]} ${RAINBOW[0]}y${RAINBOW[1]}o${RAINBOW[2]}u${RAINBOW[3]} ${RAINBOW[4]}f${RAINBOW[5]}o${RAINBOW[0]}r${RAINBOW[1]} ${RAINBOW[2]}p${RAINBOW[3]}l${RAINBOW[4]}a${RAINBOW[5]}y${RAINBOW[0]}i${RAINBOW[1]}n${RAINBOW[2]}g${NC}"
echo -e "${CYAN}May your bugs be features and your features be hilarious${NC}"
echo

# Easter egg
if [ $(($RANDOM % 100)) -eq 42 ]; then
  echo -e "${YELLOW}🥚 EASTER EGG: You found the meaning of life!${NC}"
  echo -e "${YELLOW}   (It's probably a missing semicolon)${NC}"
fi