name: Virus-Deconstructor CI

on:
  push:
    paths:
      - 'tools/virus-deconstructor/**'
      - '.github/workflows/virus-deconstructor-ci.yml'
  pull_request:
    paths:
      - 'tools/virus-deconstructor/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Virus-Deconstructor
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Check formatting
      run: |
        cd tools/virus-deconstructor
        cargo fmt -- --check
    
    - name: Run clippy
      run: |
        cd tools/virus-deconstructor
        cargo clippy -- -D warnings
    
    - name: Run tests
      run: |
        cd tools/virus-deconstructor
        cargo test --verbose
    
    - name: Build release
      run: |
        cd tools/virus-deconstructor
        cargo build --release --verbose
    
    - name: Test extraction
      run: |
        cd tools/virus-deconstructor
        mkdir -p test-output
        echo 'function add(a, b) { return a + b; }' > test.js
        ./target/release/virus-deconstructor scan --root . --out test-output/genes.ndjson
        cat test-output/genes.ndjson
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: virus-deconstructor-${{ github.sha }}
        path: |
          tools/virus-deconstructor/target/release/virus-deconstructor
          tools/virus-deconstructor/test-output/

  build-multi-platform:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Build
      run: |
        cd tools/virus-deconstructor
        cargo build --release
    
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: virus-deconstructor-${{ matrix.os }}-${{ github.sha }}
        path: |
          tools/virus-deconstructor/target/release/virus-deconstructor
          tools/virus-deconstructor/target/release/virus-deconstructor.exe